fixtures:
  repositories:
    stdlib:        "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    apache:        "git://github.com/puppetlabs/puppetlabs-apache.git"
    foreman:       "git://github.com/theforeman/puppet-foreman.git"
    concat:        "git://github.com/puppetlabs/puppetlabs-concat"
    certs:         "git://github.com/katello/puppet-certs.git"
    common:        "git://github.com/katello/puppet-common.git"
  symlinks:
    crane: "#{source_dir}"
