--- 
  :log_dir: /var/log/katello-installer
  :log_name: capsule-installer.log
  :log_level: :debug
  :no_prefix: true
  :answer_file: "./config/answers.capsule-installer.yaml"
  :installer_dir: "."
  :default_values_dir: "./config"
  :modules_dir: "./modules"
  :hooks_dir: "./hooks"
  :colors: true
  :order:
    - certs
    - capsule
