--- 
  :log_dir: /var/log/katello-installer
  :log_name: katello-devel-installer.log
  :log_level: :debug
  :no_prefix: true
  :answer_file: "./config/answers.katello-devel-installer.yaml"
  :installer_dir: "."
  :modules_dir: "./modules"
  :default_values_dir: "./config"
  :colors: true
  :order:
    - certs
    - katello_devel
  :password: l7VtnWiPeKe412o2CVBM6yVbTkKGh6L_CKx4_zBkmUE
